site_name: xtalk
docs_dir: .
repo_url: https://github.com/xcc-zach/xtalk
repo_name: xcc-zach/xtalk
theme:
  name: material
  language: en
  icon:
    repo: fontawesome/brands/github
extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: 简体中文
      link: /zh/
      lang: zh
plugins:
  - search:
      separator: '[\s\u200b\-]'
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
          site_name: X-Talk Documentation
        - locale: zh
          name: 简体中文
          build: true
          site_name: X-Talk文档
          link: /zh/
          nav_translations:
            Home: 首页
            Tutorial: 教程
            Quickstart: 快速开始
            Testing: 测试
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Tutorial:
      - Testing: tutorial/testing.md