from __future__ import annotations

import ast
from pathlib import Path


DOCS_ROOT = Path(__file__).resolve().parent
REPO_ROOT = DOCS_ROOT.parent
SERVER_DOCS_ROOT = DOCS_ROOT / "api" / "server"
SAMPLE_APP_ROOT = REPO_ROOT / "examples" / "sample_app"


def _doc_path_for_module(module_name: str) -> Path:
    parts = module_name.split(".")
    if module_name == "xtalk":
        return Path("xtalk") / "index.md"
    return Path(*parts[:-1]) / f"{parts[-1]}.md"


def _sample_app_doc_entries() -> list[tuple[str, Path]]:
    entries: list[tuple[str, Path]] = []
    for module_name in _sample_app_modules():
        entries.append((module_name, _doc_path_for_module(module_name)))
    return entries


def _sample_app_modules() -> list[str]:
    modules: set[str] = set()
    for source_path in sorted(SAMPLE_APP_ROOT.glob("*.py")):
        tree = ast.parse(source_path.read_text(encoding="utf-8"), filename=str(source_path))
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    if alias.name == "xtalk" or alias.name.startswith("xtalk."):
                        modules.add(alias.name)
            elif (
                isinstance(node, ast.ImportFrom)
                and node.level == 0
                and node.module
                and (node.module == "xtalk" or node.module.startswith("xtalk."))
            ):
                modules.add(node.module)
    return sorted(modules)


def _module_doc_markdown(module_name: str, language: str) -> str:
    title = module_name if language == "en" else f"{module_name} API"
    return "\n".join(
        [
            "<!-- This file is auto-generated by server_index_hook.py. -->",
            f"# {title}",
            "",
            f"::: {module_name}",
            "",
        ]
    )


def _link_target(doc_path: Path, language: str) -> Path:
    if language == "en":
        return doc_path
    if doc_path.name == "index.md":
        return doc_path.with_name("index.zh.md")
    return doc_path.with_suffix(".zh.md")


def _render_index(language: str) -> str:
    doc_entries = _sample_app_doc_entries()
    lines = [
        "<!-- This file is auto-generated by server_index_hook.py. -->",
        "# Server API" if language == "en" else "# 服务端 API",
        "",
    ]
    lines.extend(
        f"- [`{module_name}`]({_link_target(doc_path, language).as_posix()})"
        for module_name, doc_path in doc_entries
    )
    lines.append("")
    return "\n".join(lines)


def _write_if_changed(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8")


def _prune_generated_server_docs() -> None:
    for path in SERVER_DOCS_ROOT.rglob("*.md"):
        if path in {SERVER_DOCS_ROOT / "index.md", SERVER_DOCS_ROOT / "index.zh.md"}:
            continue
        path.unlink()

    for directory in sorted(
        [path for path in SERVER_DOCS_ROOT.rglob("*") if path.is_dir()],
        key=lambda item: len(item.parts),
        reverse=True,
    ):
        if directory == SERVER_DOCS_ROOT:
            continue
        try:
            directory.rmdir()
        except OSError:
            pass


def _write_module_docs() -> None:
    for module_name, doc_path in _sample_app_doc_entries():
        if doc_path.name == "index.md":
            zh_path = doc_path.with_name("index.zh.md")
        else:
            zh_path = doc_path.with_suffix(".zh.md")

        _write_if_changed(SERVER_DOCS_ROOT / doc_path, _module_doc_markdown(module_name, "en"))
        _write_if_changed(SERVER_DOCS_ROOT / zh_path, _module_doc_markdown(module_name, "zh"))


def build_server_indexes() -> None:
    _prune_generated_server_docs()
    _write_module_docs()
    _write_if_changed(SERVER_DOCS_ROOT / "index.md", _render_index("en"))
    _write_if_changed(SERVER_DOCS_ROOT / "index.zh.md", _render_index("zh"))


def on_config(config, **kwargs):
    build_server_indexes()
    return config


if __name__ == "__main__":
    build_server_indexes()
