from __future__ import annotations

import ast
from pathlib import Path


DOCS_ROOT = Path(__file__).resolve().parent
REPO_ROOT = DOCS_ROOT.parent
PACKAGE_ROOT = REPO_ROOT / "src" / "xtalk"
SERVING_ROOT = PACKAGE_ROOT / "serving"
SERVER_DOCS_ROOT = DOCS_ROOT / "api" / "server"
SAMPLE_APP_ROOT = REPO_ROOT / "examples" / "sample_app"


def _serving_doc_entries() -> list[tuple[str, Path]]:
    entries: list[tuple[str, Path]] = []
    for source_path in sorted(SERVING_ROOT.rglob("*.py")):
        relative_path = source_path.relative_to(PACKAGE_ROOT)
        module_parts = relative_path.with_suffix("").parts
        if source_path.name == "__init__.py":
            module_name = ".".join(("xtalk",) + relative_path.parts[:-1])
            doc_path = Path("xtalk").joinpath(*relative_path.parts[:-1], "index.md")
        else:
            module_name = ".".join(("xtalk",) + module_parts)
            doc_path = Path("xtalk").joinpath(*relative_path.parts[:-1], f"{source_path.stem}.md")
        entries.append((module_name, doc_path))
    return entries


def _sample_app_modules() -> list[str]:
    modules: set[str] = set()
    for source_path in sorted(SAMPLE_APP_ROOT.glob("*.py")):
        tree = ast.parse(source_path.read_text(encoding="utf-8"), filename=str(source_path))
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    if alias.name == "xtalk" or alias.name.startswith("xtalk."):
                        modules.add(alias.name)
            elif (
                isinstance(node, ast.ImportFrom)
                and node.level == 0
                and node.module
                and (node.module == "xtalk" or node.module.startswith("xtalk."))
            ):
                modules.add(node.module)
    return sorted(modules)


def _render_index(language: str) -> str:
    sample_modules = _sample_app_modules()
    doc_entries = _serving_doc_entries()

    if language == "zh":
        lines = [
            "<!-- This file is auto-generated by server_index_hook.py. -->",
            "# 服务端 API",
            "",
            "本节用于展示 `xtalk.serving` 的内部 Python 参考文档。",
            "",
            "该目录下的页面在文档构建时自动更新：`mkdocs-autoapi` 负责生成各个",
            "子模块页面，`server_index_hook.py` 负责刷新本页并补齐导航链接。",
            "",
            "若需完善这部分文档，应直接更新 `src/xtalk/serving/` 中的 Python",
            "docstring。",
            "",
            "## `examples/sample_app` 直接导入的 Xtalk 模块",
            "",
        ]
        lines.extend(f"- `{module}`" for module in sample_modules)
        lines.extend(
            [
                "",
                "## `xtalk.serving` 子模块文档",
                "",
                "以下链接会在每次文档构建时根据当前源码树自动更新：",
                "",
            ]
        )
    else:
        lines = [
            "<!-- This file is auto-generated by server_index_hook.py. -->",
            "# Server API",
            "",
            "This section hosts the internal Python reference for `xtalk.serving`.",
            "",
            "The pages in this directory are refreshed during documentation builds:",
            "`mkdocs-autoapi` generates the submodule pages and `server_index_hook.py`",
            "rewrites this index with links to them.",
            "",
            "Update the Python docstrings in `src/xtalk/serving/` to improve this",
            "documentation.",
            "",
            "## Xtalk modules imported directly by `examples/sample_app`",
            "",
        ]
        lines.extend(f"- `{module}`" for module in sample_modules)
        lines.extend(
            [
                "",
                "## `xtalk.serving` submodule docs",
                "",
                "These links are regenerated from the current source tree on every build:",
                "",
            ]
        )

    lines.extend(f"- [`{module_name}`]({doc_path.as_posix()})" for module_name, doc_path in doc_entries)
    lines.append("")
    return "\n".join(lines)


def _write_if_changed(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8")


def build_server_indexes() -> None:
    _write_if_changed(SERVER_DOCS_ROOT / "index.md", _render_index("en"))
    _write_if_changed(SERVER_DOCS_ROOT / "index.zh.md", _render_index("zh"))


def on_config(config, **kwargs):
    build_server_indexes()
    return config


if __name__ == "__main__":
    build_server_indexes()
